// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyjxiemgksmllltftcvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55anhpZW1na3NtbGxsdGZ0Y3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjUwMDUsImV4cCI6MjA2NzUwMTAwNX0.Nu4RuvbOFuhtFX6wL1wmvH-sO6CK_B_t1A9mIoFl9fs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});